### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [michaeltroger/greenpass-android#183]
...as we can only use Java 11 or 17 now: https://monitor.f-droid.org/builds/log/com.michaeltroger.gruenerpass/53#site-footer

ref: https://github.com/michaeltroger/greenpass-android/commit/8e070ce400f9c3d355fd74a71007f1ec1b414316

But there's an upgrade to Debian Bookworm in progress so we might be able to install Java 19 or 21 from Debian Sid then.

anyway, which new feature you need from 21 that was not in 17?

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/45f788be85af35fde977ef0242d95ec5c73590fa

**Comment by michaeltroger** [comment]
Hi! Thx for pinging!

No particular reason other than just wanting to stay up-to-date. It's an LTS version and it works nicely with Gradle, Github CI and generally with Android development already so I didn't expect any issues. It's supposed to improve build speeds...

Would be nice if F-Droid could support LTS versions at least.
Anyhow I downgraded to Java 17 now https://github.com/michaeltroger/greenpass-android/commit/b9fb054c02fc8d2fa07dcb6cd17c86629ecea6b8 since I still want to support F-Droid.
https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14506

For future reference: Do you know if there is any publicly available info/documentation on supported Java versions for F-Droid CI?

**Comment by licaon-kter** [comment]
The CI tries to follow the main server, so it's the same, look into .gitlab-ci.yml file in the fdroiddata repo

**Comment by michaeltroger** [comment]
Thx
