### ISSUE TITLE
[QUESTION] Extracted/enlarged Aztec code != the original one

### ISSUE THREAD

**Issue by revuwa** [michaeltroger/greenpass-android#262]
I have a small problem of understanding and hope you can enlighten me.
I'm currently using the debug build of [this issue](https://github.com/michaeltroger/greenpass-android/issues/251) and realized, that the enlarged version of my Aztec code is not the same as the original code from the pdf.

Hope the following picture shows what I mean:
![barcode_compare](https://github.com/michaeltroger/greenpass-android/assets/7300276/9326652b-ca2d-4c36-bfdf-5102742cab99)

Ich zoomed the original code to more or less the same size as the enlarged one (above).
For privacy reasons I just made a little spyhole with 3% gaussian blur and hope this is enough to see, that the two codes, which should be the same, (IMHO) are completely different. 🤨

While this is not a big deal, 'cause it seems to work properly and could be scanned correctly with valid data, but I hope you can understand my surprise?

Is it possible, that the app spit out the extracted code just in another format (Aztec code 652 -> 323 or whatever ‍🤷‍♀️)?
Or should the matter be investigated?

**Comment by michaeltroger** [comment]
This is expected behavior since the app generates barcodes with default settings of the ZXing library, which might differentiate to the settings from the original barcode. The barcode content is identical for readers. Mostly the differences can be explained by different settings for error correction. So in short - a barcode that holds the same data can quite likely look differently, depending on the barcode generator. Some companies even put a logo on the barcode.
Since for reading devices it won't make a difference this is not something that is planned to be tackled.

BTW: This matter is also explained in the Store entry
https://github.com/michaeltroger/greenpass-android/blob/57/fastlane/metadata/android/en-US/full_description.txt#L32-L33
https://play.google.com/store/apps/details?id=com.michaeltroger.gruenerpass

**Comment by revuwa** [comment]
> BTW: This matter is also explained in the Store entry https://github.com/michaeltroger/greenpass-android/blob/57/fastlane/metadata/android/en-US/full_description.txt#L32-L33 https://play.google.com/store/apps/details?id=com.michaeltroger.gruenerpass

Thanks a lot for clarifying and shame on me that I missed the text in the Store entry. Sorry for that 🙏
