### ISSUE TITLE
QR code not extracted when it is very small

### ISSUE THREAD

**Issue by webworxshop** [michaeltroger/greenpass-android#54]
Hi,

Thanks for the app, it great to have a simple offline way to do this.

I imported my NZ vaccine certificate into the app, but it doesn't recognise and extract the QR code. Could be that it is too small for the scanner?

For reference our vaccine certificates look like this:

![NZ vaccine certificate](https://covid19.govt.nz/assets/Images/vaccine-campaign/My-Vaccine-Pass-example__ResizedImageWzcyMCw0MDVd.png)

...with the PDF version I imported being formatted exactly like the center image.

Thanks again, please let me know if you need more information or if I can help in any way.

**Comment by michaeltroger** [comment]
Hi!

Thx for the demo image. Yes, the issue is most likely that it's too small. In the EU the code is much bigger. I'm using the popular ZXing library for detecting barcodes and I noticed issues like this with small barcodes.
I'm currently looking into a way to let the user select where in the document the barcode can be found. That could potentially fix this issue. I'll let you know if I have anything to try out

Michael

**Comment by webworxshop** [comment]
Thanks, that sounds promising. I'm happy to give it a test when you have something.

Thanks also for the quick response!

**Comment by michaeltroger** [comment]
The approach with selecting the barcode location turned out to become too complex for this free time project.
Sorry to say but I don't have a solution for this.
External help is appreciated though (please align with me before investing too much time though)

**Comment by michaeltroger** [comment]
The new version 4 of the app will come with improved barcode recognition. This is as good as it will get for now.
If it would still not work with this version, then I can not offer a solution.
