### ISSUE TITLE
Slovenian qr

### ISSUE THREAD

**Issue by Zoki60** [michaeltroger/greenpass-android#60]
QR Code is not extracted for the Slovenian Vaccine Certificate if there are more than 2 vaccine

**Comment by michaeltroger** [comment]
The app only supports one qr code per document, if no QR code is detected then most likely because it's too small see https://github.com/michaeltroger/greenpass-android/issues/54
If the QR code is extracted but not the desired one, please check https://github.com/michaeltroger/greenpass-android/issues/56
