### ISSUE TITLE
Feature Request: Be included in "open with"-list

### ISSUE THREAD

**Issue by VictorieeMan** [michaeltroger/greenpass-android#74]
Problem to adress: Not part of the "open with"-list

Description: Opening a PDF file doesn't invite the user to open with "Green Pass". Only way to open PDFs seem to be through the app. An auto add to wallet and read, would be a practical automation.

Green Pass PDF Wallet version
2.3.2
One UI version  
4.1  
Android version
12

**Comment by michaeltroger** [comment]
Hi, sorry for the late reply. I made it like this on purpose.
From outside of the app you can actually "open" documents with the app with the "share" functionality.
So go to a filemanager and share the pdf. The green pass app should be offered.

The reason why I removed the open PDFs functionality is that it might be misleading - since the app actually is not a regular PDF viewer but rather a wallet that stores a copy of the PDF inside its own app space.
If you feel comfortable compiling the Android app yourself from this source code I can provide you with instructions - it's rather easy to achieve this. If I recall correctly it's just adding a few lines of code.

At this time I don't plan to integrate it in the store version though. But if more people think this is a good behaviour then please reopen this issue. Thx!

**Comment by michaeltroger** [comment]
I changed my mind on this one. It will be part of the next version. Enjoy!

**Comment by VictorieeMan** [comment]
Cool 😎
